language: node_js
node_js: node
services: mongodb
env: MONGODB_URI=mongodb://localhost:27017/dogs
deploy:
  provider: heroku
  app:
    master: best-in-dogs
  api_key:
    secure: SYCj9dszqPQfEApzKlEpvdyY8ngQHvkLt+NIiVud3TItupkCXqA/VcEaziuN7mbYLhlDaUrsNwfs6asCi4shIDTWivXZuZyluskwlFZW5FJAErt8xUlFqRgQDHZeZEANYow8H/82RhtUBMuPooLUq9jR+rENbfA5uaisMWBrFMA5szShUKcmWcNXGoOKvJTvRxbx85ROXudAiJjLssQBmPPgbUKVeYAmXnPuewqjXS3gVkuTF/uPgt0QUXNHUDy5Z97cd5S8qmCxszr3JkH++hzj916jq9gjhbSosfVJVe/9QBwOz7Y+7UJ7/4ImdPnRvaIxiNJYz3HZ/+UPV1Uu3t7/Eqgh2rhHHvCjVQy4eYg5pk5hZXOWAjQWHAfox1GW7J8iFfYQszDuN7LFtWJn2vnwXDSbhunI1YbTQ5G7WJT92rPf/2RBquzIKyg+fWPT0Xb6s8wm5n7hba3mot5Q48EbCCIlNl779ynAQVu+3mCD8XpFG0NDp9KR+MZ6mNv8aeuevjqS2cVnTMsWaasHk0DBvCLOOcqEuVH9Pi/2fXNwZJJaugCta1dlZxwQqAQmZlkdNUbhXfJMQCnBlCkmajl2ftAADz1ZrzqV7kQ0M3Ux2e+d4YisSmz9hqnOjZXAHptjgx5OR4tEGsnGMv/JvOPXBnTQvpxuq14sBdJlqd8=
